include:
    - pages
    - posts
name: Daveed Silva
tagline: Personal website for Daveed Silva
author: daveed
dest: build
copy:
    - public
exclude:
    - .draft.md
theme:
    - layouts/tailwind
css: tailwind
engine: default
version: '2'
